"""empty message

Revision ID: e39f789a8764
Revises: 
Create Date: 2018-05-11 06:57:15.408312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39f789a8764'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sonnen_battery',
    sa.Column('consumption', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('gridConsumption', sa.Integer(), nullable=True),
    sa.Column('pacTotal', sa.Integer(), nullable=True),
    sa.Column('production', sa.Integer(), nullable=True),
    sa.Column('rsoc', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usoc', sa.Integer(), nullable=True),
    sa.Column('uAC', sa.Integer(), nullable=True),
    sa.Column('uBat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sonnen_battery')
    # ### end Alembic commands ###
